In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
import torch.optim as optim
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from torch.utils.data.dataset import random_split
from torchvision import datasets
from sklearn.metrics import confusion_matrix
import seaborn as sns
import PIL
from sklearn.model_selection import train_test_split

In [14]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(5, 10)
        self.fc2 = nn.Linear(10, 10)
        self.fc3 = nn.Linear(10, 10)
        self.fc4 = nn.Linear(10,10)
        self.fc5 = nn.Linear(10,1)

    def forward(self, x):
        out = F.relu(self.fc1(x))
        out = F.relu(self.fc2(out))
        out = F.relu(self.fc3(out))
        out = F.relu(self.fc4(out))
        out = torch.relu(self.fc5(out))
        return out

In [3]:
net = Net()
optimizer = optim.SGD(net.parameters(), lr=0.01, momentum=0.5)

In [4]:
max_epochs = 50

random_seed = 671
torch.manual_seed(random_seed)

In [5]:
data = pd.read_csv("BS_Simulated_data.csv").iloc[:, 1:]
data = data.astype(np.float32) 

In [6]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                   y, 
                                   test_size=0.33, 
                                   random_state=42)
                                   

In [8]:
X_train = torch.tensor(X_train.values)
X_test = torch.tensor(X_test.values)
y_train = torch.tensor(y_train.values)
y_test = torch.tensor(y_test.values)

In [9]:
X_train[0]

tensor([4.7106e+02, 1.2479e+02, 1.1075e-01, 2.4949e-02, 7.6812e-01])

In [10]:
loss_list, acc_list = [], []
loss_list_val, acc_list_val = [], []
criterion = nn.MSELoss()

for epoch in range(max_epochs):
    #TODO: set the net to train mode:
    net.train()

    epoch_loss = 0.0
    correct = 0

    # for computation of avg loss
    for i in range(len(X_train)):
        X = X_train[i]
        y = y_train[i]
        # X, y = X.to(device), y.to(device)

        optimizer.zero_grad()
        ##TODO: pass the data into the network and store the output
        out = net(X)
        ##TODO: Calculate the cross entropy loss between the output and target
        loss = criterion(out, y)
        ##TODO: Perform backpropagation

        loss.backward()
        optimizer.step()

        ##TODO: Get the prediction from the output
        ##TODO: Calculate the correct number and add the number to correct

    ##TODO: Add the loss to epoch_loss.
        epoch_loss += loss.item() 

    ##TODO: calculate the average loss
    avg_loss = epoch_loss / len(X_train)
    ##TODO: calculate the average accuracy
    ##TODO: append average epoch loss to loss list
    loss_list.append(avg_loss)
    ##TODO: append average accuracy to accuracy list
    # validation
    ##TODO: set the model to eval mode
    net.eval()
    with torch.no_grad():
        loss_val = 0.0
        correct_val = 0


        for i in range(len(X_test)):
            input_test = X_test[i]
            output_test = y_test[i]
            # input_test, output_test = input_test.to(device), output_test.to(device)
            ##TODO: pass the data into the network and store the output
            out = net(data)
            ##TODO: Calculate the cross entropy loss between the output and target 
            loss = criterion(out, labels)
            ##TODO: Get the prediction from the output
            loss_val += loss.item()


        ##TODO: calculate the average loss of validation
        avg_loss_val = loss_val / len(X_test)
        ##TODO: calculate the average accuracy of validation
        ##TODO: append average epoch loss to loss list of validation
        loss_list_val.append(avg_loss_val)
        ##TODO: append average accuracy to accuracy list of validation
        acc_list_val.append(avg_acc_val)
    print('[epoch %d] loss: %.5f accuracy: %.4f val loss: %.5f val accuracy: %.4f' % (epoch + 1, avg_loss, avg_loss_val))

/Users/macongcong/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/loss.py:536: UserWarning: Using a target size (torch.Size([])) that is different to the input size (torch.Size([1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


TypeError: linear(): argument 'input' (position 1) must be Tensor, not DataFrame

In [16]:
net(X_train[1])

tensor([nan], grad_fn=<ExpBackward0>)

In [ ]:
X_train[0]

In [ ]:
data

In [18]:
net(X_train[1])

tensor([nan], grad_fn=<ExpBackward0>)